# ~/.tmux.conf, see tmux(1)

## usable terminal
set-option -g history-limit 248832
set-option -g base-index 1

## navigation
# vim
set-option -g status-keys vi
set-option -g mode-keys vi
bind-key Escape copy-mode

## colours
# statusbar colour and contents
set-option -g status-style bg=black,fg=yellow,default

# window titles
set-option -g window-status-current-style fg=white,bg=default
set-option -g window-status-style fg=brightblack,bg=default

# pane border
set-option -g pane-active-border-style fg=brightmagenta
set-option -g pane-border-style fg=brightgreen

# message text
set-option -g message-style fg=brightmagenta,bg=black

# clock
set-option -g clock-mode-colour green
set-option -g clock-mode-style 24

# bell
set-option -g window-status-bell-style fg=black,bg=red

